language: go

go:
  - "1.12.x"

addons:
  apt:
    packages:
      - rpm
      - snapd

env:
  - PATH=/snap/bin:$PATH

before_install:
  - go get -u golang.org/x/lint/golint

install:
  - sudo snap install snapcraft --classic
  - env GO111MODULE=on go get ./...

git:
  depth: 1

notifications:
  email: false

script:
  - env GO111MODULE=on make all
  - env GO111MODULE=on make lint
  - env GO111MODULE=on make vet
  - env GO111MODULE=on make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
